#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 11:17:53 2023

Script that runs f000f analysis of group of power spectra.
PSD estimates obtained using the pwelch function in Matlab.

@author: stojanovic
"""

# import the required packages
import numpy as np
import scipy.io as spio
import mat73
from fooof import F000FGroup

# define the frequencies and spectra from the group
file_prefix = ''

sub_dir     = 'home/mpib/stojanovic/PSDDATA/pwelch_spec_data/'
#sub_dir  = 'home/mpib/stojanovic/PSDDATA/
#sub_dir = '/Users/stojanovic/Documents/Projects/MaxPlanck/Data/'

# subject list
subjects   = ['113922']; #add rest later

for s in range(0, np.size(subs)):sub = subs[s]
    
    # import PSD data obtained from pwelch function in Matlab
    fname    = sub_dir + 'CompVar_PSD_spec_' + str(sub) + '.mat'
    
    data     = mat73.loadmat(fname) 
    
    freqs    = data['fs']
    spectra  = data['spec']
    
    # check the shape of the loaded data
    print(freqs.shape)
    print(spectra.shape)
    
    # F000FGroup takes a matrix of the shape [n_spectra,n_freqs]
    fg = F000FGroup(peak_width_limits = [1,8], min_peak_height = 0.05, max_n_peaks = 8)
    
    # define the frequency range
    freq_range      = [3,40] # could also be 2 Hz - test outs
    
    
    fg.fit(freqs, spectra, [3,40])
    fg.print_results()
    #fg.plot()
    
    
    # can also conduct further analyses in/with fooof
    
    # fit a power spectrum model
    fm = FOOOF(peak_width_limits=[2, 8])
    fm.fit(freqs, spectra, [3, 30])
